## Development infrastructure for running and testing the Debezium UI
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.4
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - network
  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:2.4
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092
    networks:
      - network
  db-pg:
    container_name: db-pg
    image: quay.io/debezium/example-postgres:2.4
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - network
  db-mysql:
    container_name: db-mysql
    image: quay.io/debezium/example-mysql:2.4
    ports:
      - "63306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysql
    networks:
      - network
  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.4
    ports:
      - 8083:8083
      - 9012:9012 
      - 8778:8778
    depends_on:
      - kafka
      - db-pg
      - db-mysql
    links:
      - kafka
      - db-pg
      - db-mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=pg_connect_configs
      - OFFSET_STORAGE_TOPIC=pg_connect_offsets
      - STATUS_STORAGE_TOPIC=pg_connect_statuses
      - JMXPORT=9012
      - JMXHOST=0.0.0.0
      - ENABLE_JOLOKIA=true
    volumes:
      - ./config/java/java.txt:/usr/share/crypto-policies/DEFAULT/java.txt
      - ./config/java/java.security:/etc/java/java-11-openjdk/java-11-openjdk-11.0.20.0.8-1.fc37.x86_64/conf/security/java.security
    networks:
      - network
  debezium-ui:
    container_name: debezium-ui
    image: quay.io/debezium/debezium-ui:2.4
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://connect:8083
    depends_on:
      - connect
    networks:
      - network

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:stable
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "zsolution123"
    command: -Dpidfile.path=/dev/null 
    networks:
      - network
networks:
  network:
    external: false
