version: '3'

services:

  zookeeper:

    container_name: zookeeper

    image: quay.io/debezium/zookeeper:2.4

    ports:

     - 2181:2181

     - 2888:2888

     - 3888:3888

    networks:

      - network

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

    networks:

      - network

  connect:

    container_name: connect

    image: quay.io/debezium/connect:2.4

    ports:

      - 8083:8083

      - 9012:9012

      - 8778:8778

    depends_on:

      - kafka


    links:

      - kafka

    environment:

      - BOOTSTRAP_SERVERS=kafka:9092

      - GROUP_ID=1

      - CONFIG_STORAGE_TOPIC=pg_connect_configs

      - OFFSET_STORAGE_TOPIC=pg_connect_offsets

      - STATUS_STORAGE_TOPIC=pg_connect_statuses

      - JMXPORT=9012

      - JMXHOST=0.0.0.0

      - ENABLE_JOLOKIA=true

      # - ENABLE_DEBEZIUM_SCRIPTING=true

      # - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension

      # - ENABLE_JOLOKIA=true

    volumes:

      - ./config/java/java.txt:/usr/share/crypto-policies/DEFAULT/java.txt

      - ./config/java/java.security:/etc/java/java-11-openjdk/java-11-openjdk-11.0.20.0.8-1.fc37.x86_64/conf/security/java.security

    networks:

      - network

  debezium-ui:

    container_name: debezium-ui

    image: quay.io/debezium/debezium-ui:2.4

    ports:

      - "8080:8080"

    environment:

      KAFKA_CONNECT_URIS: http://connect:8083

    depends_on:

      - connect

    networks:

      - network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8088:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - network

  kafka-manager:

    container_name: kafka-manager

    image: hlebalbau/kafka-manager:stable

    restart: always

    ports:

      - "9000:9000"

    depends_on:

      - zookeeper

      - kafka

    environment:

      ZK_HOSTS: "zookeeper:2181"

      APPLICATION_SECRET: "zsolution123"

    command: -Dpidfile.path=/dev/null

    networks:

      - network

networks:

  network:

    external: false